version: '3'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_DEFAULT_PORT:-5432}
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgresdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4pass}
    ports:
      - ${PGADMIN_PORT:-8080}:${PGADMIN_LISTEN_PORT:-8080}
    depends_on:
      - db
    networks:
      - postgres-compose-network

volumes:
  pgdata:

networks:
  postgres-compose-network:
    driver: bridge
