version: '3'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_DEFAULT_PORT:-5432}
    environment:
      POSTGRES_USER: ${DATABASE_USER:-}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-}
      POSTGRES_DB: ${DATABASE_NAME:-}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - ${ADMINER_PORT:-8080}:${ADMINER_DEFAULT_PORT:-8080}

volumes:
  pgdata:
