version: '3'

services:
  pgsql:
    image: postgres:alpine
    restart: always
    env_file: env/.env.development
    container_name: 'pgsql'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
